version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    reviewers:
      - amimart
      - ccamel
    assignees:
      - amimart
      - ccamel
  - package-ecosystem: github-actions
    directory: /src
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    reviewers:
      - amimart
      - ccamel
    assignees:
      - amimart
      - ccamel
